### PR TITLE
Refactoring

### PR DESCRIPTION
**Pull request by cpuguy96**
* Refactors code for better readability and debugging 
* Leaves original functionality

### CODE REVIEW

**Comment by jhaco** [comment]
Where are the files placed? Do you have to manually create the parseIn folder now?

**Comment by cpuguy96** [comment]
The `parseIn` folder is already contained in the project directory when checked out. There is no reason to create the folder again if you are expecting the `.sm` and `.ogg` files to already be there. Otherwise, the program will run, find no files in the `parseIn` folder, then terminate without parsing anything.

I guess one reason to still create the folder is if the user deletes the folder and tries to run the program. They will find there is no `parseIn` folder and can't parse the files. But ideally, you would want to the user to specify the input directory that their files are in. That way you don't have to hard code a specific folder to find all the files in.

**Comment by jhaco** [comment]
One reason I hardcode the input folder is because I prefer to not have to specify a new input folder every time I run the script. I want to automate as much as I can just by running the script alone straight out the box. No typing inputs, _nothing_.

"_There is no reason to create the folder again if you are expecting the .sm and .ogg files to already be there. Otherwise, the program will run, find no files in the parseIn folder, then terminate without parsing anything_." I think that's exactly how I intended it to work. The current script checks for the necessary folders and if they aren't there when they should be, it'll create the folders for you and terminate since the newly created, _correct_ folders have nothing in them. Maybe I should have included a message that lets people know to put the files in that folder once it's made, but I felt the instructions on the README are self-explanatory. The check is quick and takes no time at all, so even if the parseIn folder is already there, it makes no difference runtime-wise.

I do see the use in specifying different input folders. Maybe you have certain input files of differing quality and want to test different data sets. That's fine. I could write a Windows batch file to accept arguments for input folders (and maybe output folders) for the script so that the user would only have to edit the batch file and run it. However, I really prefer the script to be automated and hands-off the way I currently have it set up.

**Comment by cpuguy96** [comment]
> One reason I hardcode the input folder is because I prefer to not have to specify a new input folder every time I run the script. I want to automate as much as I can just by running the script alone straight out the box. No typing inputs, nothing.
>

The usual way to accept user input for a python script is to use `argparse` (https://docs.python.org/2/library/argparse.html). That way the user can specify any inputs from a CLI without the need to manually change the code. You can even set default values in the case an input to a parameter is not passed. I didn't add that into this commit, but it should be added since it is way more user friendly.

> I think that's exactly how I intended it to work. The current script checks for the necessary folders and if they aren't there when they should be, it'll create the folders for you
>

You can do that but it doesn't make much sense. In the viewpoint of a blackbox with an inputs/outputs, you should expect inputs to the program regardless. If there isn't any input, why should the program run in the first place? Instead, it should send an error message saying there isn't any input so the user can correct their mistake. Again, I should have added that to this commit.

> Maybe I should have included a message that lets people know to put the files in that folder once it's made
>

You can do that, but it would just be easier to require the user to provide valid input to the script. Output is fine to not specify since you can create any empty output folder and store your results there.

> I could write a Windows batch file to accept arguments for input folders (and maybe output folders) for the script so that the user would only have to edit the batch file and run it. However, I really prefer the script to be automated and hands-off the way I currently have it set up.
>

Just use `argsparse` to take in inputs. That way, any shell script can call upon the python script specifying arguments (ex: `python smfile_parser.py --input some/input/dir --output some/output/dir`)

**Comment by jhaco** [comment]
Alright, fair point. I've added the argparse arguments you specified and tested your improvements, so I'm going to push this request and commit a few more lines to master afterwards for argparse functionality.

* If no arguments are given, the script defaults to parseIn/parseOut. (What I want) 
* If either argument is given, it'll attempt to run using the default input/output folder where none is specified.
* If the input folder is missing, a message stating so will print and the script terminates.
* If the input folder is found, but the output folder is missing, the script will generate the specified folder.

Otherwise the script will not generate any other folders.

I also really like the new, leaner code implementations. You removed about 50 lines of code of the original. Very nice.

**Pull request merged**
